version: '3.7'

services:

  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: "1000:1000"
    container_name: app
    image: jjuanrivvera99/laravel:mysql-alpine
    restart: always
    depends_on:
      - redis
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  queue:
    restart: always
    depends_on:
      - redis
    image: jjuanrivvera99/laravel:mysql-alpine
    environment:
      CONTAINER_ROLE: "queue"
    volumes:
      - "./:/var/www/"
    networks:
      - app-network

  scheduler:
    restart: always
    depends_on:
      - redis
    image: jjuanrivvera99/laravel:mysql-alpine
    environment:
      CONTAINER_ROLE: "scheduler"
    volumes:
      - "./:/var/www/"
    networks:
      - app-network

  node:
    image: jjuanrivvera99/node:alpine
    restart: always
    build:
      context: docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

  redis-data:
    driver: local
